apiVersion: apps/v1
kind: Deployment
metadata:
  name: diners-amqp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: diners-amqp
  template:
    metadata:
      labels:
        app: diners-amqp
    spec:
      containers:
        - name: mensageria
          image: 066510737035.dkr.ecr.us-east-1.amazonaws.com/diners-ecr-repo:latest
          ports:
            - containerPort: 61616
          env:
            - name: PORT
              value: "61616"
---
apiVersion: v1
kind: Service
metadata:
  name: diners-amqp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 61616
  selector:
    app: diners-amqp