apiVersion: apps/v1
kind: Deployment
metadata:
  name: diners-sonarqube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: diners-sonarqube
  template:
    metadata:
      labels:
        app: diners-sonarqube
    spec:
      containers:
        - name: sonar
          image: 066510737035.dkr.ecr.us-east-1.amazonaws.com/diners-ecr-repo:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: diners-sonarqube
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: diners-sonarqube